### ISSUE TITLE
[FB] Criar projeto ListBuy no GitHub

### ISSUE THREAD

**Issue by msgovea** [msgovea/listbuy#5]

**Comment by talitasc** [comment]
teste

**Comment by msgovea** [comment]
# Projeto List Buy

## Descrição Projeto

_Projeto desenvolvido para avaliação do 6º período do curso de Sistemas de Informação da PUC Campinas, com avaliação das matérias:_

-  Sistemas de Informação II
- Banco de Dados II
- Análise de Sistemas II 

## **Equipe**

- Mateus Sauer Govêa
- Murilo Lourenço
- Talita Castro
- Aline Rabelo

## **Links úteis**

- [Casos de Uso](https://drive.google.com/open?id=1b8XNYj3LzvHget7RSH8K80VoM5OGMBZ2O_weCKa_T7E)
